<?php
/**
 * @file
 * Test implementations for Views Rules.
 */

/**
 * Implements hook_views_api().
 */
function views_rules_test_views_api() {
  return array(
    'version' => '3.0',
  );
}

/**
 * Iterable implementation for testing iterator display.
 */
class ViewsRulesTestIterable implements ViewsRulesIterable {
  public $rows = array();

  /**
   * Evaluates a view row in the loop.
   */
  public function evaluateRow(array $data) {
    $this->rows[] = $data;
  }

  public function reset() {
    $this->rows = array();
    return $this;
  }

  /**
   * Implements hook_autoload_info().
   */
  function views_rules_test_autoload_info() {
    return array(
      'ViewsRulesTestIterable' => 'views_rules_test.module',
    );
  }
}
